### ISSUE TITLE
Question about the re-implement

### ISSUE THREAD

**Issue by Jie-su** [visenger/DataGuards#1]
Dear Visenger,

I am a student who wanna re-implement your project, but I meet some problems of running code on my computer. Can I ask why "NoiseHOSP.scala" can not be run.

If I can not run the scripts, can I use your experiment result and cite your paper?

Best Wishes,

Jie,

**Comment by visenger** [comment]
Hi Jie,
NoiseHOSP.scala is responsible for the random noise introduction into the HOSP dataset. The path to the dataset should be provided in the configuration file: application.conf
I already prepared the ["dirty" version](https://github.com/visenger/clean-and-dirty-data/tree/master/HOSP-1K/dirty) of this dataset. You can find the clean data [here](https://github.com/visenger/clean-and-dirty-data/blob/master/HOSP-1K/hospital_1k.csv). 

Sure, you can use the experiment results from the paper and cite the paper: "Visengeriyeva, L and Akbik, A and Kaul, Manohar "Improving Data Quality by Leveraging Statistical Relational Learning". In: International Conference on Information Quality, 22-23 June, 2016, Ciudad Real, Spain."

Best regards,
Larysa

**Comment by Jie-su** [comment]
Dear Visenger,

If I wanna run the evaluation file to get the experiment figure, how can I get the 'log-noise-hosp-1' file?

Best Wishes,

Jie,

**Comment by visenger** [comment]
Jie, please have a look at this [repository](https://github.com/visenger/noiselog).

**Comment by Jie-su** [comment]
Thanks
